### ISSUE TITLE
Plugin not working with  PXIe-6341

### ISSUE THREAD

**Issue by hkim09** [open-ephys-plugins/nidaq-plugin#1]
I see "no choice" in the voltage range selection menu, and I see in the debug console,  I see below message

DAQmx Error: Minimum is greater than or equal to the maximum. Ensure the maximum value is greater than the minimum value. If using a custom scale, ensure that the scaled maximum is greater than the scaled minimum.
Property: DAQmx_AI_Min
Corresponding Value:  0.0
Property: DAQmx_AI_Max
Corresponding Value:  0.0
Channel Name: PXI1Slot4/ai15

Task Name: AITask_PXI31412766

Thanks!

**Comment by medengineer** [comment]
Have you tried using this module with SpikeGLX before? We just ordered this module and will test and integrate it as soon as it arrives. In the mean time, if you have success using this module with SpikeGLX we can start looking into the code now. Thanks!

**Comment by hkim09** [comment]
SpikeGLX can detect the card correctly, and I can run it without errors. I have not checked whether I see valid signals using a function generator (just checked close-to-zero signals go). I'll test it if I can see valid signals early next week.

**Comment by hkim09** [comment]
Hi. I just checked that I can see both analog and digital input signals correctly.

**Comment by medengineer** [comment]
Hi. We received the module and found the bug: we were assuming voltage ranges were at least+/- 1V and your device supports +/- 0.2V. We've updated the code however we don't have the cable to run a proper test. If you could give it a test at your earliest convenience to confirm that would be helpful. Thanks!
