### ISSUE TITLE
PCI-MIO-16E-4: DAQmx Error: Requested value is not a supported value for this property

### ISSUE THREAD

**Issue by jamesbigelow** [open-ephys-plugins/nidaq-plugin#10]
I have a BNC-2110 connected to a PCI-MIO-16E-4 card with NI-DAQmx Version NI-DAQmx 19.0 (which is the latest supported version for this card). The NI-DAQmx module in the OpenEphys GUI works as expected (e.g., the card is recognized, the controls work, etc.) until I start acquisition/writing to disk. Then the message below is printed to the debugger, and there are not continuous files recorded to the record node (the folder is empty other than a settings.xml file). Data acquisition also works in NI MAX. Any ideas? Is there a modification of the plug-in that might fix? Or does the card lack required functionality (it is quite old)? I know this isn't one of the tested devices listed in the documentation, but I had an extra one so decided to try. 

Enabling processors...
Source node received enable signal
Source node received enable signal
DAQmx Error: Requested value is not a supported value for this property. The property value may be invalid because it conflicts with another property.
Property: DAQmx_SampTimingType
Requested Value: DAQmx_Val_SampClk
Possible Values: DAQmx_Val_OnDemand

Task Name: DITask_PXI10812005

Status Code: -200077

**Comment by medengineer** [comment]
Hi,

Thanks for reporting this. Looks like it’s an issue w/ the digital line configuration for this particular card. 

If you disable (toggle the buttons gray) on all the digital inputs in the NIDAQmx plugin do you still get the same error? You should be able to at least record from all of the analog inputs that way. In the meantime, I’ll look into configuring the digital line properly for this card. 

It would also be helpful to know if the card works fine with SpikeGLX software.

**Comment by medengineer** [comment]
I believe the line causing the error occurs [here](https://github.com/open-ephys-plugins/nidaq-plugin/blob/master/Source/NIDAQComponents.cpp#L489). A couple quick fixes to try if you are able to compile the NIDAQmx plugin from source: 

1. Changing the ```trigName``` parameter to ```NULL``` to default to the internal clock. 
2. Changing the if statement to default to ```False``` in order to skip this configuration step entirely.

**Comment by jamesbigelow** [comment]
Thanks! This was helpful. 

| Changing the if statement to default to False in order to skip this configuration step entirely.
This basically worked. I commented out the 'if' statement to skip the config step, then compiled the plugin, and then was able to acquire data without the error messages. *Unfortunately*, by compiling the GUI and plugins from source (NIDAQmx and Neuropixels PXI), I apparently created another bug: The NPX recording directory capacity meter quickly fills to ~100% (within seconds) and the debugger prints lines indicating possible data loss every few hundred milliseconds: 
[Neuropix-PXI] NPX TIMESTAMP JUMP: 577, expected 3 or 4...Possible data loss on slot 2, probe 1 at sample number 594240
The recording directory is a nearly empty 4TB NVME drive, so there is clearly a bug somewhere. Everything else about the Neuropixels PXI plugin seems to be working properly. I have zero prior experience compiling from source, so I may have done something incorrectly here.  

Also per your suggestion, I tried SpileGLX, which recognized the PCI-MIO-16E-4 device, but had similar errors after initiating data streaming: 

[Thd 16016 CPU 1 7/15/22 11:41:37.848] DAQmx Error:
Fun=<DAQmxCfgSampClkTiming( taskDI1, ((clk1).toUtf8().constData()), p.ni.key2SetRate( p.ni.clockSource ), 10280, 10123, maxMuxedSampPerChan )>
ErrNum=<-200077>
ErrMsg='Requested value is not a supported value for this property. The property value may be invalid because it conflicts with another property.
Property: DAQmx_SampTimingType
Requested Value: DAQmx_Val_SampClk
Possible Values: DAQmx_Val_OnDemand

Task Name: TaskDI1

Status Code: -200077'.

**Comment by jsiegle** [comment]
Hi James -- did you compile the GUI in debug mode or release mode? If it's in debug mode, that explains the failure to keep up with data throughput; Neuropixels acquisition only runs smoothly in release mode.

**Comment by jamesbigelow** [comment]
Ahh thanks -- building everything in release mode solved the issue. I was able to record data from Neuropixels and NIDAQ plugins without any issues. Thanks again!
