### ISSUE TITLE
Missing header files necessary for compiling the plugin?

### ISSUE THREAD

**Issue by tkskdm2** [open-ephys-plugins/nidaq-plugin#11]
Compiling the plugin failed because the following two header files are missing: PluginInfo.h and DataThreadHeaders.h. They are called from NIDAQComponents.h, NIDAQThread.h, and OpenEphysLib.cpp. Where can I find the two header files?

**Comment by anjaldoshi** [comment]
Hi, 
Looks like  you didn't clone the plugin repo in the correct location. First, if you didn't compile the GUI from source, please do so by following [these](https://open-ephys.github.io/gui-docs/Developer-Guide/Compiling-the-GUI.html) instructions provided on the GUI docs website.
You also need to make sure the plugin is cloned in the correct directory relative to the GUI. You directory structure should look something like this: 
```
code_directory/
   plugin-GUI/
   OEPlugins/
      nidaq-plugin
```
And, make sure to follow [these](https://open-ephys.github.io/gui-docs/Developer-Guide/Compiling-plugins.html) instructions to compile the plugin. 

Let me know if you're still facing issues after this.

**Comment by tkskdm2** [comment]
Hi Anjal, 

  

Thank you so much for answering my question! I really appreciate your quick response. I could successfully compile my plugin by following your suggestion.  

 

There was one thing I needed to figure out myself, which was the location of plugin directory with respect to the plugin-GUI. To successfully compile the plugin, the following directory arrangement was necessary: 

`code_directory/plugin-GUI/ nidaq-plugin` 

Hope this would be helpful for somebody.
