### ISSUE TITLE
Request: Adding higher pre-defined sample rates

### ISSUE THREAD

**Issue by vncntprvst** [open-ephys-plugins/nidaq-plugin#17]
Hi, 
I was wondering if you could add higher sampling rates to the drop-down menu of the NIDAQ plugin.
We use a device to record ultrasonic vocalizations, and we typically set the sampling rate to 250 kHz (using Wavesurfer, in Matlab). 
I was checking if we could use the Open-Ephys Gui for that purpose.
As far as I understand the code, the new option(s) would go there:
https://github.com/open-ephys-plugins/nidaq-plugin/blob/a62f61605fa25db90ed769f1875e6199c855de2e/Source/NIDAQComponents.cpp#L140
I could build and test it myself, but I'm lazy 😅.
Thanks,
Vincent

**Comment by medengineer** [comment]
Hi,

The GUI's data processing callbacks are driven by the computer's audio card. 
I'm not aware of any audio cards > 192 kHz, otherwise it would technically be possible.
In general, we recommend using a separate piece of software (like Bonsai) to record > 30 kHz signals.

**Comment by vncntprvst** [comment]
I see. I knew I'd better ask before trying it :) 
I'll use Bonsai then.
Thanks for the reply!
