### ISSUE TITLE
Feature request: Not writing analogue channels when disabled.

### ISSUE THREAD

**Issue by FelixAntonSchneider** [open-ephys-plugins/nidaq-plugin#4]
Hi,
not sure where this should go and it's also not super urgent. But I noticed that when I disable analogue channels in the GUI, that they ignore any input signal, but that it still writes a file for all analogue channels and timestamps, just full of zeros. So it is just a useless file in this case. Might be good to make it, such that it only writes the files for enabled channels.

Cheers, 
Felix

**Comment by medengineer** [comment]
Hi Felix

Starting in v0.5.1 of the plugin-GUI you can use the new Record Node plugin to control which channels get written to disk, regardless of which channels are enabled/disabled in the NIDAQ plugin itself. For example, if you only want to enable and record the first and third analog channel from your NIDAQ module:
![RecordingWNIDAQ](https://user-images.githubusercontent.com/10275396/95137098-3a170d00-071c-11eb-910d-74cb0b6d6107.png)

**Comment by FelixAntonSchneider** [comment]
Great, thanks!
